services:
  network:
    build: .
    container_name: network
    restart: always
    ports:
      - "8080:8000"
    environment:
      - TZ=${DOCKER_TZ}
    volumes:
      - ${DOCKER_CFG_DIR}/network:/data
    networks:
      - proxy

networks:
  proxy:
    external: true
